config/routes.rb
Rails.application.routes.draw do
  root 'resources#index'
  resources :resources
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @resources = Resource.all
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.new(params.require(:resource).permit(:name, :organization, :max_count))
    if @resource.save
      redirect_to resources_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResourcesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resources/index.html.erb
<h1>I AM IN THE INDEX PAGE</h1>

<%= link_to "New Resource", new_resource_path %>

<% @resources.each do |resource| %>
  <br>
  <%= resource.name %>
  <%= resource.organization %>
  <%= resource.max_count %>
<% end %>

app/views/resources/new.html.erb
<form method="get" class="form-inline" role="form" action="/resources">
  <div class="form-group">
    <label class="sr-only" for="name">Name:</label>
    <input name="name" type="text" class="form-control" id="name" placeholder="Enter name">
  </div>
  <div class="form-group">
    <label class="sr-only" for="organization">Organization:</label>
    <input name="organization" type="text" class="form-control" id="organization" placeholder="Enter organization">
  </div>
  <div class="form-group">
    <label class="sr-only" for="max_count">Maximum Count:</label>
    <input name="max_count" type="number" class="form-control" id="max_count" placeholder="Enter count">
  </div>
  <div class="button">
    <button type="submit">Create Resource</button>
    <a href="http://localhost:3000/resources">
      <input type="button" value="Cancel" />
    </a>
  </div>
</form>